[[main]]
none = "none"

[[main]]
name = "2025 Event Plan"
pageRef = "timeLine"
identifier = "qkBUakZUpC"
weight = 2

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "VjedDE0Fmj"
weight = 3

[[main]]
name = "Contact Us"
pageRef = "contactUs"
identifier = "3s5BGcLa8w"
weight = 6

[[main]]
name = "Event"
pageRef = "event"
identifier = "8xNFEvvqtP"
weight = 4

[[main]]
name = "Our Sponsor"
pageRef = "ourSponsor"
identifier = "Ks4TCG77WB"
weight = 5

[[main]]
name = "About"
pageRef = "about"
identifier = "vk7KDyZfVQ"
weight = 1

[[footer]]
none = "none"
