[[main]]
none = "none"

[[main]]
name = "Registration Link"
pageRef = "registrationLink"
identifier = "qkBUakZUpC"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "VjedDE0Fmj"
weight = 3

[[main]]
name = "Contact Us"
pageRef = "contactUs"
identifier = "3s5BGcLa8w"
weight = 5

[[main]]
name = "Event"
pageRef = "event"
identifier = "8xNFEvvqtP"
weight = 2

[[main]]
name = "Our Sponsor"
pageRef = "ourSponsor"
identifier = "Ks4TCG77WB"
weight = 4

[[footer]]
none = "none"
